### ISSUE TITLE
Restructure fields to avoid deep nesting?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/stats#2]
I had a quick look at this and was wondering why the two-level approach was taken? Historically, there was always the aim to keep things as flat as possible (e.g. for visualization in JSON Software, but I also see that this is simpler in STAC Browser) so I'd like to propose a different structure:

```json
    "stats:catalogs": {
      "count": 1,
      "versions": {
        "1.0.0": 1
      }
    },
    "stats:collections": {
      "count": 1,
      "versions": {
        "1.0.0": 1
      }
    },
    "stats:items": {
      "count": 4,
      "versions": {
        "1.0.0": 4
      },
      "extensions": {
        "https://stac-extensions.github.io/eo/v1.0.0/schema.json": 1
      },
      "assets": {
        "image/jpeg": 3,
        "image/png": 1,
        "image/tiff; application=geotiff; profile=cloud-optimized": 3
      }
    }
  },
```

That basically just makes it one level less deep.

Three other questions came up while writing this:
1. The objects are not defined yet, i.e. what goes into stats:items etc? At least the README doesn't provide it.
2. How many catalogs actually mix STAC versions? Is this only relevant to static catalogs?
3. Are media types for assets the (only/most important) thing to group by?

**Comment by tschaub** [comment]
> wondering why the two-level approach was taken

I've been using a tool that you can point at an endpoint and it generates stats that conform with this extension's schema.  The idea was that you could use this tool and paste the output into a `stats` member in your JSON.

I can update the tool to conform with your proposed schema changes though.

> The objects are not defined yet, i.e. what goes into stats:items etc? At least the README doesn't provide it.

Yeah, documentation needs fleshing out.  Details in the schema, but not yet in the markdown.

> How many catalogs actually mix STAC versions? Is this only relevant to static catalogs?

It looks like it is not uncommon.  https://earth-search.aws.element84.com/v0 is a mix of 1.0.0-beta.2 and 1.0.0-rc.3.  https://ard.maxar.com/samples/catalog.json is a mix of 0.8.1, 1.0.0-beta.2, and 1.0.0.  https://franklin.nasa-hsi.azavea.com/ is a mix of 1.0.0-beta.2 and 1.0.0.

Ideally, by having more visibility into this, people will be motivated to upgrade.

> Are media types for assets the (only/most important) thing to group by?

I've found `type` to be the most commonly populated of the optional fields (though it too is sometimes absent).  It feels like the most meaningful field to me (for understanding the distribution of assets "types" out there).
